# .github/workflows/publish.yml
name: Publish Package

on:
    push:
        branches:
            - main # Ganti dengan nama branch utama Anda jika berbeda

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14" # Ganti dengan versi Node.js yang sesuai
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm install

            - name: Lint and test
              run: |
                  npm run lint
                  npm test

            - name: Build package
              run: npm run build # Sesuaikan dengan script build Anda

            - name: Publish to NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
