name: Publish Package

on:
    push:
        branches:
            - main # Sesuaikan dengan nama branch utama Anda

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14" # Sesuaikan dengan versi Node.js yang Anda gunakan
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm install

            - name: Lint and test
              run: |
                  npm run lint
                  npm test

            - name: Build package
              run: npm run build # Sesuaikan dengan skrip build Anda

            - name: Publish to NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create GitHub Release
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git tag v${{ steps.build.outputs.version }}
                  git push origin v${{ steps.build.outputs.version }}
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
